apiVersion: v1
kind: Service
metadata:
  name: api-nodejs-service
  namespace: so1-fase2
spec:
  selector:
    app: api-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: ClusterIP