apiVersion: v1
kind: Service
metadata:
  name: api-python-service
  namespace: so1-fase2
spec:
  selector:
    app: api-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP