version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: monitor_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: josseline
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: monitorServicios 
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata:
