apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-socket
  namespace: so1-fase2
  labels:
    app: api-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-socket
  template:
    metadata:
      labels:
        app: api-socket
        tier: api
    spec:
      containers:
      - name: api-socket
        image: josselinemontecinos7/api-socket-fase2:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: "34.41.95.190"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "metricas_db"
        - name: DB_PORT
          value: "3306"
        - name: PORT
          value: "4000"

---
apiVersion: v1
kind: Service
metadata:
  name: api-socket-service
  namespace: so1-fase2
spec:
  selector:
    app: api-socket
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
