apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
  namespace: so1-fase2
  labels:
    app: api-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-python
  template:
    metadata:
      labels:
        app: api-python
        tier: api
    spec:
      containers:
      - name: api-python
        image: josselinemontecinos7/api-python:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "34.41.95.190"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "metricas_db"
        - name: DB_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  name: api-python-service
  namespace: so1-fase2
spec:
  selector:
    app: api-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP