apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nodejs
  namespace: so1-fase2
  labels:
    app: api-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-nodejs
  template:
    metadata:
      labels:
        app: api-nodejs
        tier: api 
    spec:
      containers:
      - name: api-nodejs
        image: josselinemontecinos7/api-node-fase2:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "34.41.95.190"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          value: "metricas_db"
        - name: DB_PORT
          value: "3306"
        - name: PORT
          value: "3000"

---
apiVersion: v1
kind: Service
metadata:
  name: api-nodejs-service
  namespace: so1-fase2
spec:
  selector:
    app: api-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 
  type: ClusterIP