version: '3.8'

services:
  monitor-go:
    image: josselinemontecinos7/api-go-monitor
    container_name: monitor_go_fase2
    ports:
      - "6000:6000"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    privileged: true
    security_opt:
      - "apparmor=unconfined"
      - "seccomp=unconfined"
    environment:
      - PROC_PATH=/host/proc
