apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: so1-fase2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/mysql-data